In [1]:
import glob
import os
import cv2 
import matplotlib.pyplot as plt
import numpy as np
from utils import prepareObjPoints, plotImage, findBoard, CameraMatrix, scale_intrinsics
# Get the current working directory
root = os.getcwd()
print("Current working directory:", root)

# Use relative path to navigate to the images directory
landscape_directory = os.path.join(root, "landscape")
portrait_directory = os.path.join(root, "portrait")
print("Landscape directory:", landscape_directory)
print("Portrait directory:", portrait_directory)

images_landscape = []
images_landscape.extend(glob.glob(os.path.join(landscape_directory, f"*.JPG")))
print("Number of Landscape Images:",len(images_landscape))

images_portait = []
images_portait.extend(glob.glob(os.path.join(portrait_directory, f"*.JPG")))
print("Number of Portrait Images:",len(images_portait))




Current working directory: /Users/bakuljangley/Documents/ResearchAssignment/VPRMethods/CameraCaliberation
Landscape directory: /Users/bakuljangley/Documents/ResearchAssignment/VPRMethods/CameraCaliberation/landscape
Portrait directory: /Users/bakuljangley/Documents/ResearchAssignment/VPRMethods/CameraCaliberation/portrait
Number of Landscape Images: 30
Number of Portrait Images: 34


In [2]:
# #the image resolution was too high, i'll have to use resized images. 
# #makes sense to resize to mast3r resolution and process
# #i should also resize to actual image dimensions and check intrinsics

#these would be different for portrait and landscape images 

# new_width = 384
# new_height = 512


image_path="/Users/bakuljangley/Documents/ResearchAssignment/VPRMethods/CameraCaliberation/portrait/IMG_2434.JPG"
image = cv2.imread(image_path)
# resized = cv2.resize(image, (new_width, new_height), interpolation=cv2.INTER_AREA)
# plotImage(resized)
# plotImage(image)

print(image.shape)

#exampleUsage of findBoard
# ret, corners=findBoard("/Users/bakuljangley/Documents/ResearchAssignment/VPRMethods/CameraCaliberation/landscape/IMG_2451.JPG", verbose=True)

(4032, 3024, 3)


In [3]:
new_width = 384
new_height = 512

# findBoard("/Users/bakuljangley/Documents/ResearchAssignment/VPRMethods/CameraCaliberation/portrait/IMG_2439.JPG", verbose=True)

a = 9
b = 6
square_size = 0.024
objp = prepareObjPoints(a,b,square_size) # prepare object points, like (0,0,0), (1,0,0), (2,0,0) ....,(6,5,0)

# Arrays to store object points and image points from all the images.
objpoints = [] # 3d point in real world space
imgpoints = [] # 2d points in image plane.

for image in images_portait:
    ret, corners = findBoard(image, new_width=new_width, new_height=new_height)
    if ret:
        
        objpoints.append(objp)
        imgpoints.append(corners)


ret, mtx, dist, rvecs, tvecs = cv2.calibrateCamera(objpoints, imgpoints,tuple([new_width,new_height]) , None, None)
print("CAMERA MATRIX PORTRAIT\n",mtx)

K = CameraMatrix(mtx[0,0], mtx[1,1], mtx[0,2], mtx[1,2])
K_scaled = scale_intrinsics(K, new_width, new_height, 4032, 3024)
print("K\n", K)
print("K Scaled\n", K_scaled)


CAMERA MATRIX PORTRAIT
 [[222.52821253   0.         222.93543881]
 [  0.         220.66645189 260.3655876 ]
 [  0.           0.           1.        ]]
K
 [[222.52821253   0.         222.93543881]
 [  0.         220.66645189 260.3655876 ]
 [  0.           0.           1.        ]]
K Scaled
 [[2.33654623e+03 0.00000000e+00 2.34082211e+03]
 [0.00000000e+00 1.30331123e+03 1.53778425e+03]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]


In [4]:
new_width = 512
new_height = 384

a = 9
b = 6
square_size = 0.024
objp = prepareObjPoints(a,b,square_size) # prepare object points, like (0,0,0), (1,0,0), (2,0,0) ....,(6,5,0)

# Arrays to store object points and image points from all the images.
objpoints = [] # 3d point in real world space
imgpoints = [] # 2d points in image plane.

for image in images_landscape:
    ret, corners = findBoard(image)
    if ret:
        
        objpoints.append(objp)
        imgpoints.append(corners)


ret, mtx, dist, rvecs, tvecs = cv2.calibrateCamera(objpoints, imgpoints,tuple([new_width,new_height]) , None, None)
print("CAMERA MATRIX LANDSCAPE\n",mtx)





CAMERA MATRIX LANDSCAPE
 [[345.69228143   0.         260.92439734]
 [  0.         343.62710482 191.36550125]
 [  0.           0.           1.        ]]


In [5]:
K = CameraMatrix(mtx[0,0], mtx[1,1], mtx[0,2], mtx[1,2])
K_scaled = scale_intrinsics(K, new_width, new_height, 4032, 3024)
print("K\n", K)
print("K Scaled\n", K_scaled)

K
 [[345.69228143   0.         260.92439734]
 [  0.         343.62710482 191.36550125]
 [  0.           0.           1.        ]]
K Scaled
 [[2.72232672e+03 0.00000000e+00 2.05477963e+03]
 [0.00000000e+00 2.70606345e+03 1.50700332e+03]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
